version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: agent-manager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  agent-server:
    build:
      context: .
      target: server
    container_name: agent-server
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - ENV=development
      - SERVER_ADDRESS=:8080
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agent-manager:
    build:
      context: .
      target: manager
    container_name: agent-manager
    environment:
      - REDIS_ADDR=redis:6379
      - ENV=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./archive:/app/archive
      - ./run-agent.sh:/app/run-agent.sh:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: agent-manager-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: agent-manager-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    profiles:
      - monitoring

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: agent-manager-network